### ISSUE TITLE
Slight delay when starting Firefox 29

### ISSUE THREAD

**Issue by Iy204** [claytron/pentadactyl-solarized#18]
I upgraded to Firefox 29 found the problem. Use your theme, when I open Firefox will get stuck for a few seconds. Although only a small problem, but it is annoying. I'm not sure Pentadactyl extended itself, or theme. Your theme is very beautiful, I've used used to it.

**Comment by claytron** [comment]
This issue has gotten worse, creating a new window can take up to a couple of minutes. I'm going to remove the `hi clear`. If you are using this as your main color scheme, this doesn't cause any adverse behavior anyway.

**Comment by blueyed** [comment]
Thanks!
